# Generated by Django 5.2.15 on 2026-09-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('symbol', models.CharField(max_length=24, unique=True)),
                ('market', models.CharField(default='NGX', max_length=32)),
                ('description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('previous_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ipo_demo', 'IPO / Demo'), ('disabled', 'Disabled')], default='ipo_demo', max_length=16)),
                ('is_demo_data', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='investments_symbol_a53726_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimum_subscription', models.PositiveIntegerField(default=10)),
                ('opens_at', models.DateField(blank=True, null=True)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Demo subscription', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipo', to='investments.asset')),
            ],
        ),
    ]
