# Generated by Django 5.2.15 on 2026-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_demo_data',
            field=models.BooleanField(default=True, verbose_name='synthetic data'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ipo_demo', 'IPO / Simulated'), ('disabled', 'Disabled')], default='ipo_demo', max_length=16),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='status',
            field=models.CharField(default='Simulated subscription', max_length=32),
        ),
    ]
