# Generated by Django 5.2.15 on 2026-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_asset_is_demo_data_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, choices=[('banking', 'Banking'), ('telecom', 'Telecommunications'), ('consumer_goods', 'Consumer Goods'), ('industrial', 'Industrial Goods'), ('oil_gas', 'Oil & Gas'), ('insurance', 'Insurance'), ('agriculture', 'Agriculture'), ('conglomerate', 'Conglomerates'), ('healthcare', 'Healthcare'), ('real_estate', 'Real Estate & Construction'), ('utilities', 'Utilities & Power')], max_length=32),
        ),
    ]
