# Generated by Django 5.2.15 on 2026-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_asset_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ipo_demo', 'IPO / Simulated'), ('not_listed', 'Not Listed'), ('disabled', 'Disabled')], default='ipo_demo', max_length=16),
        ),
    ]
