# Generated by Django 5.2.15 on 2026-09-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('account_status', models.CharField(default='Demo Active', max_length=32)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('demo_only', 'Demo Only'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='demo_only', max_length=24)),
                ('email_verification_placeholder', models.BooleanField(default=False)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
