# Generated by Django 5.2.15 on 2026-09-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_account_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=24),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField()),
                ('id_type', models.CharField(choices=[('bvn', 'Bank Verification Number (BVN)'), ('nin', 'National Identity Number (NIN)'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=20)),
                ('id_number', models.CharField(max_length=32)),
                ('id_document', models.FileField(upload_to='kyc/documents/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='kyc/selfies/')),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
