# Generated by Django 5.2.15 on 2026-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_kyc_status_kycsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verification_placeholder',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
