# Generated by Django 5.2.15 on 2026-09-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_email_verification_placeholder_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='approval_email_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='approval_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
