from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import User
from django.core.management.base import BaseCommand
from django.utils import timezone

from investments.models import Asset, IPO
from payments.services import simulate_deposit
from trading.models import FeeSchedule, TradingSetting
from wallet.services import get_or_create_wallet

SIMULATED_NOTE = "Simulated equity card for marketplace and portfolio flows. Data is simulated and not an official offer."
IPO_NOTE = "Simulated IPO-style opportunity for product testing. Data is simulated and not an official offer."
NOT_LISTED_NOTE = "Simulated pre-IPO card for product testing. This company has not filed for listing on the NGX; there is no open subscription window and this is not an official offer."


class Command(BaseCommand):
    help = "Seed VestNaija demo data."

    def handle(self, *args, **options):
        today = timezone.now().date()
        assets = [
            # --- Banking ---
            {
                "symbol": "ZENITH",
                "name": "Zenith Bank Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("48.50"),
                "previous_price": Decimal("47.10"),
                "minimum_quantity": 1,
                "available_quantity": 150000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "GTCO",
                "name": "Guaranty Trust Holding Company Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("62.80"),
                "previous_price": Decimal("60.35"),
                "minimum_quantity": 1,
                "available_quantity": 140000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "ACCESSCORP",
                "name": "Access Holdings Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("24.10"),
                "previous_price": Decimal("23.40"),
                "minimum_quantity": 1,
                "available_quantity": 200000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "UBA",
                "name": "United Bank for Africa Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("31.55"),
                "previous_price": Decimal("30.20"),
                "minimum_quantity": 1,
                "available_quantity": 175000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "FBNH",
                "name": "FBN Holdings Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("29.85"),
                "previous_price": Decimal("28.90"),
                "minimum_quantity": 1,
                "available_quantity": 160000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "STANBIC",
                "name": "Stanbic IBTC Holdings Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("68.00"),
                "previous_price": Decimal("65.50"),
                "minimum_quantity": 1,
                "available_quantity": 80000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "GLOBUSBNK",
                "name": "Globus Bank Plc",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("15.00"),
                "previous_price": Decimal("13.50"),
                "minimum_quantity": 50,
                "available_quantity": 400000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("15.00"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=14)},
            },
            {
                "symbol": "CORONATION",
                "name": "Coronation Merchant Bank Limited",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("22.50"),
                "previous_price": Decimal("20.80"),
                "minimum_quantity": 20,
                "available_quantity": 250000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("22.50"), "minimum_subscription": 20, "opens_at": today + timedelta(days=4), "closes_at": today + timedelta(days=20)},
            },
            {
                "symbol": "TITANTRUST",
                "name": "Titan Trust Bank Limited",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("12.00"),
                "previous_price": Decimal("10.90"),
                "minimum_quantity": 50,
                "available_quantity": 350000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("12.00"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=17)},
            },
            {
                "symbol": "PROVIDUS",
                "name": "Providus Bank Limited",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("9.75"),
                "previous_price": Decimal("8.60"),
                "minimum_quantity": 100,
                "available_quantity": 500000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("9.75"), "minimum_subscription": 100, "opens_at": today + timedelta(days=6), "closes_at": today + timedelta(days=27)},
            },
            {
                "symbol": "PARALLEX",
                "name": "Parallex Bank Limited",
                "sector": Asset.Sector.BANKING,
                "current_price": Decimal("8.50"),
                "previous_price": Decimal("7.40"),
                "minimum_quantity": 100,
                "available_quantity": 450000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("8.50"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=12)},
            },
            # --- Telecommunications ---
            {
                "symbol": "MTNN",
                "name": "MTN Nigeria Communications Plc",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("245.00"),
                "previous_price": Decimal("239.00"),
                "minimum_quantity": 1,
                "available_quantity": 100000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "AIRTELAFRI",
                "name": "Airtel Africa Plc",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("2150.00"),
                "previous_price": Decimal("2080.00"),
                "minimum_quantity": 1,
                "available_quantity": 40000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "9MOBILE",
                "name": "Emerging Markets Telecommunication Services Plc (9mobile)",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("45.00"),
                "previous_price": Decimal("41.20"),
                "minimum_quantity": 50,
                "available_quantity": 200000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("45.00"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=16)},
            },
            {
                "symbol": "GLOBACOM",
                "name": "Globacom Limited",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("380.00"),
                "previous_price": Decimal("355.00"),
                "minimum_quantity": 10,
                "available_quantity": 60000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("380.00"), "minimum_subscription": 10, "opens_at": today + timedelta(days=8), "closes_at": today + timedelta(days=29)},
            },
            {
                "symbol": "IPNX",
                "name": "ipNX Nigeria Limited",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("62.00"),
                "previous_price": Decimal("57.80"),
                "minimum_quantity": 25,
                "available_quantity": 140000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("62.00"), "minimum_subscription": 25, "opens_at": today, "closes_at": today + timedelta(days=13)},
            },
            {
                "symbol": "SMILECOM",
                "name": "Smile Communications Nigeria Limited",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("28.50"),
                "previous_price": Decimal("25.90"),
                "minimum_quantity": 40,
                "available_quantity": 220000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("28.50"), "minimum_subscription": 40, "opens_at": today + timedelta(days=2), "closes_at": today + timedelta(days=19)},
            },
            {
                "symbol": "ZINOX",
                "name": "Zinox Technologies Plc",
                "sector": Asset.Sector.TELECOM,
                "current_price": Decimal("19.75"),
                "previous_price": Decimal("17.60"),
                "minimum_quantity": 50,
                "available_quantity": 260000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("19.75"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=15)},
            },
            # --- Consumer Goods ---
            {
                "symbol": "NESTLE",
                "name": "Nestle Nigeria Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("1450.00"),
                "previous_price": Decimal("1390.00"),
                "minimum_quantity": 1,
                "available_quantity": 25000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "NB",
                "name": "Nigerian Breweries Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("41.20"),
                "previous_price": Decimal("39.80"),
                "minimum_quantity": 1,
                "available_quantity": 120000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "UNILEVER",
                "name": "Unilever Nigeria Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("38.90"),
                "previous_price": Decimal("36.50"),
                "minimum_quantity": 1,
                "available_quantity": 90000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "FLOURMILL",
                "name": "Flour Mills of Nigeria Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("58.75"),
                "previous_price": Decimal("55.00"),
                "minimum_quantity": 1,
                "available_quantity": 100000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "BUAFOODS",
                "name": "BUA Foods Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("410.00"),
                "previous_price": Decimal("395.00"),
                "minimum_quantity": 5,
                "available_quantity": 200000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("410.00"), "minimum_subscription": 20, "opens_at": today, "closes_at": today + timedelta(days=14)},
            },
            {
                "symbol": "DUFIL",
                "name": "Dufil Prima Foods Plc (Indomie)",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("145.00"),
                "previous_price": Decimal("136.00"),
                "minimum_quantity": 10,
                "available_quantity": 90000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("145.00"), "minimum_subscription": 10, "opens_at": today, "closes_at": today + timedelta(days=18)},
            },
            {
                "symbol": "HONEYFLOUR",
                "name": "Honeywell Flour Mills Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("6.20"),
                "previous_price": Decimal("5.45"),
                "minimum_quantity": 200,
                "available_quantity": 700000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("6.20"), "minimum_subscription": 200, "opens_at": today + timedelta(days=5), "closes_at": today + timedelta(days=25)},
            },
            {
                "symbol": "CHILTD",
                "name": "CHI Limited (Chivita/Hollandia)",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("210.00"),
                "previous_price": Decimal("196.00"),
                "minimum_quantity": 10,
                "available_quantity": 65000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("210.00"), "minimum_subscription": 10, "opens_at": today, "closes_at": today + timedelta(days=21)},
            },
            {
                "symbol": "NBC",
                "name": "Nigerian Bottling Company Plc",
                "sector": Asset.Sector.CONSUMER_GOODS,
                "current_price": Decimal("55.00"),
                "previous_price": Decimal("50.30"),
                "minimum_quantity": 50,
                "available_quantity": 180000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("55.00"), "minimum_subscription": 50, "opens_at": today + timedelta(days=9), "closes_at": today + timedelta(days=30)},
            },
            # --- Industrial Goods ---
            {
                "symbol": "DANGCEM",
                "name": "Dangote Cement Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("495.00"),
                "previous_price": Decimal("478.00"),
                "minimum_quantity": 1,
                "available_quantity": 60000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "WAPCO",
                "name": "Lafarge Africa Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("72.30"),
                "previous_price": Decimal("69.10"),
                "minimum_quantity": 1,
                "available_quantity": 110000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "BUACEMENT",
                "name": "BUA Cement Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("115.00"),
                "previous_price": Decimal("108.50"),
                "minimum_quantity": 1,
                "available_quantity": 95000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "NOTORE",
                "name": "Notore Chemical Industries Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("78.00"),
                "previous_price": Decimal("71.50"),
                "minimum_quantity": 20,
                "available_quantity": 130000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("78.00"), "minimum_subscription": 20, "opens_at": today, "closes_at": today + timedelta(days=16)},
            },
            {
                "symbol": "IBETOCEM",
                "name": "Ibeto Cement Company Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("34.50"),
                "previous_price": Decimal("31.20"),
                "minimum_quantity": 50,
                "available_quantity": 210000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("34.50"), "minimum_subscription": 50, "opens_at": today + timedelta(days=3), "closes_at": today + timedelta(days=23)},
            },
            {
                "symbol": "KAMIND",
                "name": "Kam Industries Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("15.20"),
                "previous_price": Decimal("13.60"),
                "minimum_quantity": 50,
                "available_quantity": 240000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("15.20"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=14)},
            },
            {
                "symbol": "CERAMICNG",
                "name": "Ceramic Manufacturers Nigeria Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("6.80"),
                "previous_price": Decimal("5.95"),
                "minimum_quantity": 100,
                "available_quantity": 320000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("6.80"), "minimum_subscription": 100, "opens_at": today + timedelta(days=6), "closes_at": today + timedelta(days=26)},
            },
            {
                "symbol": "PURECROWN",
                "name": "Purecrown Industries Plc",
                "sector": Asset.Sector.INDUSTRIAL,
                "current_price": Decimal("9.90"),
                "previous_price": Decimal("8.70"),
                "minimum_quantity": 100,
                "available_quantity": 280000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("9.90"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=19)},
            },
            {
                "symbol": "DANGREF",
                "name": "Dangote Petroleum Refinery & Petrochemicals",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("525.00"),
                "previous_price": Decimal("525.00"),
                "minimum_quantity": 10,
                "available_quantity": 0,
                "status": Asset.Status.NOT_LISTED,
                "ipo": {
                    "offer_price": Decimal("525.00"),
                    "minimum_subscription": 10,
                    "opens_at": None,
                    "closes_at": None,
                    "status": "Not Listed on NGX",
                },
            },
            {
                "symbol": "NNPCRETAIL",
                "name": "NNPC Retail Limited",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("25.00"),
                "previous_price": Decimal("22.50"),
                "minimum_quantity": 40,
                "available_quantity": 300000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("25.00"), "minimum_subscription": 40, "opens_at": today, "closes_at": today + timedelta(days=18)},
            },
            {
                "symbol": "RAINOIL",
                "name": "Rainoil Limited",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("48.50"),
                "previous_price": Decimal("45.00"),
                "minimum_quantity": 20,
                "available_quantity": 150000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("48.50"), "minimum_subscription": 20, "opens_at": today + timedelta(days=3), "closes_at": today + timedelta(days=24)},
            },
            {
                "symbol": "OVHENERGY",
                "name": "OVH Energy Marketing Plc",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("41.00"),
                "previous_price": Decimal("38.20"),
                "minimum_quantity": 25,
                "available_quantity": 180000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("41.00"), "minimum_subscription": 25, "opens_at": today, "closes_at": today + timedelta(days=15)},
            },
            {
                "symbol": "NWPETGAS",
                "name": "Northwest Petroleum & Gas Company Plc",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("19.60"),
                "previous_price": Decimal("17.90"),
                "minimum_quantity": 50,
                "available_quantity": 260000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("19.60"), "minimum_subscription": 50, "opens_at": today + timedelta(days=5), "closes_at": today + timedelta(days=26)},
            },
            # --- Oil & Gas ---
            {
                "symbol": "SEPLAT",
                "name": "Seplat Energy Plc",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("4850.00"),
                "previous_price": Decimal("4620.00"),
                "minimum_quantity": 1,
                "available_quantity": 20000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "TOTAL",
                "name": "TotalEnergies Marketing Nigeria Plc",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("620.00"),
                "previous_price": Decimal("595.00"),
                "minimum_quantity": 1,
                "available_quantity": 30000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "CONOIL",
                "name": "Conoil Plc",
                "sector": Asset.Sector.OIL_GAS,
                "current_price": Decimal("142.00"),
                "previous_price": Decimal("133.50"),
                "minimum_quantity": 1,
                "available_quantity": 45000,
                "status": Asset.Status.ACTIVE,
            },
            # --- Insurance ---
            {
                "symbol": "AIICO",
                "name": "AIICO Insurance Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("1.85"),
                "previous_price": Decimal("1.72"),
                "minimum_quantity": 100,
                "available_quantity": 800000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "NEM",
                "name": "NEM Insurance Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("6.40"),
                "previous_price": Decimal("5.95"),
                "minimum_quantity": 10,
                "available_quantity": 400000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "LEADWAY",
                "name": "Leadway Assurance Company Limited",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("145.00"),
                "previous_price": Decimal("134.00"),
                "minimum_quantity": 10,
                "available_quantity": 80000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("145.00"), "minimum_subscription": 10, "opens_at": today, "closes_at": today + timedelta(days=20)},
            },
            {
                "symbol": "CUSTODIAN",
                "name": "Custodian Investment Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("8.90"),
                "previous_price": Decimal("7.95"),
                "minimum_quantity": 100,
                "available_quantity": 500000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("8.90"), "minimum_subscription": 100, "opens_at": today + timedelta(days=4), "closes_at": today + timedelta(days=24)},
            },
            {
                "symbol": "CORNERSTONE",
                "name": "Cornerstone Insurance Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("1.15"),
                "previous_price": Decimal("0.98"),
                "minimum_quantity": 500,
                "available_quantity": 1500000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("1.15"), "minimum_subscription": 500, "opens_at": today, "closes_at": today + timedelta(days=15)},
            },
            {
                "symbol": "CHIPLC",
                "name": "Consolidated Hallmark Insurance Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("1.40"),
                "previous_price": Decimal("1.20"),
                "minimum_quantity": 500,
                "available_quantity": 1200000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("1.40"), "minimum_subscription": 500, "opens_at": today + timedelta(days=7), "closes_at": today + timedelta(days=27)},
            },
            {
                "symbol": "SOVEREIGNTRUST",
                "name": "Sovereign Trust Insurance Plc",
                "sector": Asset.Sector.INSURANCE,
                "current_price": Decimal("0.95"),
                "previous_price": Decimal("0.80"),
                "minimum_quantity": 1000,
                "available_quantity": 2000000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("0.95"), "minimum_subscription": 1000, "opens_at": today, "closes_at": today + timedelta(days=12)},
            },
            # --- Agriculture ---
            {
                "symbol": "PRESCO",
                "name": "Presco Plc",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("685.00"),
                "previous_price": Decimal("650.00"),
                "minimum_quantity": 1,
                "available_quantity": 35000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "OKOMUOIL",
                "name": "The Okomu Oil Palm Company Plc",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("560.00"),
                "previous_price": Decimal("525.00"),
                "minimum_quantity": 1,
                "available_quantity": 28000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "SAROAGRO",
                "name": "Saro Agrosciences Limited",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("14.20"),
                "previous_price": Decimal("12.60"),
                "minimum_quantity": 100,
                "available_quantity": 260000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("14.20"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=17)},
            },
            {
                "symbol": "ELEPHANTGRP",
                "name": "Elephant Group Plc",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("3.60"),
                "previous_price": Decimal("3.05"),
                "minimum_quantity": 200,
                "available_quantity": 600000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("3.60"), "minimum_subscription": 200, "opens_at": today + timedelta(days=5), "closes_at": today + timedelta(days=22)},
            },
            {
                "symbol": "WACOT",
                "name": "WACOT Limited (WACOT Rice)",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("22.00"),
                "previous_price": Decimal("19.80"),
                "minimum_quantity": 50,
                "available_quantity": 190000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("22.00"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=14)},
            },
            {
                "symbol": "LIVESTOCK",
                "name": "Livestock Feeds Plc",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("2.10"),
                "previous_price": Decimal("1.85"),
                "minimum_quantity": 500,
                "available_quantity": 1000000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("2.10"), "minimum_subscription": 500, "opens_at": today + timedelta(days=8), "closes_at": today + timedelta(days=28)},
            },
            {
                "symbol": "CRESTAGRO",
                "name": "Crest Agro Products Limited",
                "sector": Asset.Sector.AGRICULTURE,
                "current_price": Decimal("9.40"),
                "previous_price": Decimal("8.10"),
                "minimum_quantity": 100,
                "available_quantity": 300000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("9.40"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=19)},
            },
            # --- Conglomerates ---
            {
                "symbol": "TRANSCORP",
                "name": "Transnational Corporation Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("18.60"),
                "previous_price": Decimal("17.10"),
                "minimum_quantity": 10,
                "available_quantity": 300000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "UACN",
                "name": "UAC of Nigeria Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("29.40"),
                "previous_price": Decimal("27.80"),
                "minimum_quantity": 1,
                "available_quantity": 85000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "SCOA",
                "name": "SCOA Nigeria Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("3.20"),
                "previous_price": Decimal("2.75"),
                "minimum_quantity": 200,
                "available_quantity": 500000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("3.20"), "minimum_subscription": 200, "opens_at": today, "closes_at": today + timedelta(days=15)},
            },
            {
                "symbol": "JOHNHOLT",
                "name": "John Holt Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("1.85"),
                "previous_price": Decimal("1.55"),
                "minimum_quantity": 500,
                "available_quantity": 900000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("1.85"), "minimum_subscription": 500, "opens_at": today + timedelta(days=4), "closes_at": today + timedelta(days=25)},
            },
            {
                "symbol": "CHELLARAMS",
                "name": "Chellarams Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("2.65"),
                "previous_price": Decimal("2.25"),
                "minimum_quantity": 300,
                "available_quantity": 650000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("2.65"), "minimum_subscription": 300, "opens_at": today, "closes_at": today + timedelta(days=18)},
            },
            {
                "symbol": "LEVENTIS",
                "name": "A.G. Leventis (Nigeria) Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("1.10"),
                "previous_price": Decimal("0.92"),
                "minimum_quantity": 500,
                "available_quantity": 1100000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("1.10"), "minimum_subscription": 500, "opens_at": today + timedelta(days=6), "closes_at": today + timedelta(days=26)},
            },
            {
                "symbol": "PZCUSSONS",
                "name": "PZ Cussons Nigeria Plc",
                "sector": Asset.Sector.CONGLOMERATE,
                "current_price": Decimal("22.50"),
                "previous_price": Decimal("19.80"),
                "minimum_quantity": 50,
                "available_quantity": 220000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("22.50"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=13)},
            },
            # --- Utilities & Power (IPO opportunities) ---
            {
                "symbol": "GEREGU",
                "name": "Geregu Power Plc",
                "sector": Asset.Sector.UTILITIES,
                "current_price": Decimal("845.00"),
                "previous_price": Decimal("810.00"),
                "minimum_quantity": 5,
                "available_quantity": 120000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("845.00"), "minimum_subscription": 10, "opens_at": today + timedelta(days=7), "closes_at": today + timedelta(days=28)},
            },
            {
                "symbol": "TRANSPWR",
                "name": "Transcorp Power Plc",
                "sector": Asset.Sector.UTILITIES,
                "current_price": Decimal("298.00"),
                "previous_price": Decimal("275.00"),
                "minimum_quantity": 5,
                "available_quantity": 180000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("298.00"), "minimum_subscription": 15, "opens_at": today, "closes_at": today + timedelta(days=10)},
            },
            {
                "symbol": "NORTHSOUTHPWR",
                "name": "North South Power Company Limited",
                "sector": Asset.Sector.UTILITIES,
                "current_price": Decimal("62.00"),
                "previous_price": Decimal("56.50"),
                "minimum_quantity": 20,
                "available_quantity": 140000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("62.00"), "minimum_subscription": 20, "opens_at": today + timedelta(days=2), "closes_at": today + timedelta(days=23)},
            },
            {
                "symbol": "EGBINPWR",
                "name": "Egbin Power Plc",
                "sector": Asset.Sector.UTILITIES,
                "current_price": Decimal("210.00"),
                "previous_price": Decimal("195.00"),
                "minimum_quantity": 10,
                "available_quantity": 90000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("210.00"), "minimum_subscription": 10, "opens_at": today, "closes_at": today + timedelta(days=20)},
            },
            {
                "symbol": "IKEJAELECTRIC",
                "name": "Ikeja Electric Plc",
                "sector": Asset.Sector.UTILITIES,
                "current_price": Decimal("55.00"),
                "previous_price": Decimal("49.80"),
                "minimum_quantity": 25,
                "available_quantity": 160000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("55.00"), "minimum_subscription": 25, "opens_at": today + timedelta(days=9), "closes_at": today + timedelta(days=30)},
            },
            # --- Healthcare ---
            {
                "symbol": "FIDSON",
                "name": "Fidson Healthcare Plc",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("18.90"),
                "previous_price": Decimal("17.40"),
                "minimum_quantity": 10,
                "available_quantity": 150000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "MAYBAKER",
                "name": "May & Baker Nigeria Plc",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("9.85"),
                "previous_price": Decimal("8.90"),
                "minimum_quantity": 10,
                "available_quantity": 130000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "NEIMETH",
                "name": "Neimeth International Pharmaceuticals Plc",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("3.15"),
                "previous_price": Decimal("2.70"),
                "minimum_quantity": 300,
                "available_quantity": 700000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("3.15"), "minimum_subscription": 300, "opens_at": today, "closes_at": today + timedelta(days=16)},
            },
            {
                "symbol": "MORISON",
                "name": "Morison Industries Plc",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("1.40"),
                "previous_price": Decimal("1.15"),
                "minimum_quantity": 500,
                "available_quantity": 950000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("1.40"), "minimum_subscription": 500, "opens_at": today + timedelta(days=4), "closes_at": today + timedelta(days=24)},
            },
            {
                "symbol": "EMZOR",
                "name": "Emzor Pharmaceuticals Limited",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("45.00"),
                "previous_price": Decimal("40.50"),
                "minimum_quantity": 20,
                "available_quantity": 110000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("45.00"), "minimum_subscription": 20, "opens_at": today, "closes_at": today + timedelta(days=14)},
            },
            {
                "symbol": "JUHEL",
                "name": "Juhel Pharmaceuticals Limited",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("18.60"),
                "previous_price": Decimal("16.40"),
                "minimum_quantity": 50,
                "available_quantity": 180000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("18.60"), "minimum_subscription": 50, "opens_at": today + timedelta(days=7), "closes_at": today + timedelta(days=27)},
            },
            {
                "symbol": "CODIXPHARMA",
                "name": "Codix Pharma Limited",
                "sector": Asset.Sector.HEALTHCARE,
                "current_price": Decimal("12.30"),
                "previous_price": Decimal("10.80"),
                "minimum_quantity": 100,
                "available_quantity": 240000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("12.30"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=19)},
            },
            # --- Real Estate & Construction ---
            {
                "symbol": "UPDC",
                "name": "UPDC Plc",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("2.35"),
                "previous_price": Decimal("2.10"),
                "minimum_quantity": 100,
                "available_quantity": 900000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "JBERGER",
                "name": "Julius Berger Nigeria Plc",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("104.00"),
                "previous_price": Decimal("96.50"),
                "minimum_quantity": 1,
                "available_quantity": 70000,
                "status": Asset.Status.ACTIVE,
            },
            {
                "symbol": "UPDCRE",
                "name": "UACN Property Development Company Plc",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("3.50"),
                "previous_price": Decimal("3.00"),
                "minimum_quantity": 100,
                "available_quantity": 600000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("3.50"), "minimum_subscription": 100, "opens_at": today, "closes_at": today + timedelta(days=15)},
            },
            {
                "symbol": "LANDWEY",
                "name": "Landwey Investment Limited",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("25.00"),
                "previous_price": Decimal("22.10"),
                "minimum_quantity": 40,
                "available_quantity": 170000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("25.00"), "minimum_subscription": 40, "opens_at": today + timedelta(days=3), "closes_at": today + timedelta(days=24)},
            },
            {
                "symbol": "MIXTAAFRICA",
                "name": "Mixta Africa Plc",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("14.80"),
                "previous_price": Decimal("12.90"),
                "minimum_quantity": 50,
                "available_quantity": 200000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("14.80"), "minimum_subscription": 50, "opens_at": today, "closes_at": today + timedelta(days=18)},
            },
            {
                "symbol": "PROVIDENCEREH",
                "name": "Providence Real Homes Limited",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("8.20"),
                "previous_price": Decimal("7.10"),
                "minimum_quantity": 100,
                "available_quantity": 260000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("8.20"), "minimum_subscription": 100, "opens_at": today + timedelta(days=6), "closes_at": today + timedelta(days=26)},
            },
            {
                "symbol": "PURPLEREIT",
                "name": "Purple Real Estate Investment Trust",
                "sector": Asset.Sector.REAL_ESTATE,
                "current_price": Decimal("100.00"),
                "previous_price": Decimal("100.00"),
                "minimum_quantity": 10,
                "available_quantity": 400000,
                "status": Asset.Status.IPO_DEMO,
                "ipo": {"offer_price": Decimal("100.00"), "minimum_subscription": 10, "opens_at": today, "closes_at": today + timedelta(days=21)},
            },
        ]
        for data in assets:
            ipo_terms = data.pop("ipo", None)
            is_ipo = data["status"] in (Asset.Status.IPO_DEMO, Asset.Status.NOT_LISTED)
            default_note = NOT_LISTED_NOTE if data["status"] == Asset.Status.NOT_LISTED else (IPO_NOTE if is_ipo else SIMULATED_NOTE)
            data.setdefault("description", default_note)
            asset, _ = Asset.objects.update_or_create(symbol=data["symbol"], defaults={**data, "market": "NGX", "is_demo_data": True, "is_enabled": True})
            if ipo_terms:
                ipo_status = ipo_terms.pop("status", "IPO / Simulated")
                IPO.objects.update_or_create(asset=asset, defaults={**ipo_terms, "status": ipo_status})

        FeeSchedule.objects.update_or_create(name="Standard brokerage fee", defaults={"rate": Decimal("0.00500"), "is_active": True, "notes": "Configurable placeholder; not an official fee schedule."})
        TradingSetting.objects.update_or_create(key="trading_mode", defaults={"value": "simulated", "description": "No real securities are traded; asset prices are simulated."})

        if settings.DEBUG:
            # Login-with-known-password demo account. Only ever created on local/dev
            # (DEBUG=True); never in production, since this repo is public and the
            # password below is readable by anyone.
            user, created = User.objects.get_or_create(username="nasir@example.com", defaults={"email": "nasir@example.com", "first_name": "Nasir", "last_name": ""})
            if created:
                user.set_password("DemoPass123!")
                user.save()
                user.profile.phone = "+2348012345678"
                user.profile.accepted_terms = True
                user.profile.save()
            get_or_create_wallet(user)
            if user.wallet.total_deposited == 0:
                simulate_deposit(user, Decimal("250000.00"))
            self.stdout.write(self.style.SUCCESS(f"VestNaija demo data seeded with {len(assets)} listings. Demo login: nasir@example.com / DemoPass123!"))
        else:
            self.stdout.write(self.style.SUCCESS(f"VestNaija market data seeded with {len(assets)} listings."))
